### ISSUE TITLE
List this repo on awesome

### ISSUE THREAD

**Issue by jtagcat** [agucova/awesome-esp#2]
Can't see it [here](https://github.com/sindresorhus/awesome)
If I'm reminded, I'll add it there myself.

**Comment by agucova** [comment]
To be honest, I haven't requested it because when I was working on it initially I felt it was really incomplete. (and I still do).

But if you think's it's a good idea, I can a pull request right now

**Comment by agucova** [comment]
I'm finishing the requirements right now

**Comment by jtagcat** [comment]
Can't see it there? It died because of lack of time?

**Comment by agucova** [comment]
Nope, I actually noticed it needed a bunch more projects if it is to be considered "updated" and "hard work".

Now that I'm finally on vacations I'll be updating with newer projects, so I can create the pull request.

**Comment by agucova** [comment]
It was just merged into awesome. Tweet: https://twitter.com/awesome__re/status/1223484444629061632?s=19
